// <auto-generated />
namespace MVC_Course_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgenres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgenres));
        
        string IMigrationMetadata.Id
        {
            get { return "202109301258374_addgenres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
